
name: Deploy API

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
env:
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:

  Build:
    permissions:
     contents: 'read'
     id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sre:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sre:${{ github.run_number }}

  Deploy-api:
    runs-on: ubuntu-latest
    permissions:
     contents: 'read'
     id-token: 'write'
    needs: [Build]
    steps:
      - uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v2'
        with:
         service_account: my-service-account@311349419137.iam.gserviceaccount.com # my-service-account@my-project.iam.gserviceaccount.com
         workload_identity_provider: projects/311349419137/locations/global/workloadIdentityPools/github/providers/gke-project # "projects/123456789/locations/global/workloadIdentityPools/github/providers/my-repo"
      
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2
        with:
         version: '>= 363.0.0'

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          #gcloud auth login
          gcloud config set account data-audio-433402-f3
          gcloud container clusters get-credentials gke-cluster --zone us-central1-c  --project data-audio-433402-f3

      - name: API service account
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/api/api-service-account.yml

      # Inject var in deployment
      - name: Render Deployment YAML - API
        uses: nowactions/envsubst@v1
        with:
          input:  k8s/api/api-deployment.yml
          output: k8s/api/deployment.yml
        env:
          IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/sre:${{ github.run_number }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - name: Deploy
        run: kubectl apply -f ./k8s/api/deployment.yml
            
      - name: API service
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/api/api-service.yml

      - name: API horizontal pod autoscaler
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/api/api-hpa.yml
