
name: Deploy ISTIO

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'k8s/istio/**'
  
env:
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  istio-config:
    name: 'Istio deployment'
    permissions:
     contents: 'read'
     id-token: 'write'
    runs-on: ubuntu-latest
    needs: [terraform]

    defaults:
      run:
        working-directory: ./terraform
        shell: bash

    steps:
      - name: Setup GCP
        uses: actions/checkout@v2

      - uses: google-github-actions/auth@v2
        with:
         project_id: ${{ secrets.GKE_PROJECT }}
         workload_identity_provider: projects/311349419137/locations/global/workloadIdentityPools/github/providers/gke-project

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"
  ISTIO:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"

      - name: Deploy ISTIO
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/istio/istio-gateway-deployment.yml
